Testing Core pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: ALZ - Core
+name: ALZ
 
 on:
   # This is used to enable a workflow to be triggered manually.
@@ -54,18 +54,18 @@ jobs:
           tenant-id: ${{ secrets.ARM_TENANT_ID }}
           subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 
-      # # Run a terraform fmt to check syntax
-      # - name: Terraform Format
-      #   id: fmt
-      #   run: |
-      #     cd terraform fmt -check
+      # Run a terraform validate
+      - name: Terraform Validate
+        id: validate
+        env:
+          environment: ${{ inputs.environment }}
 
-      # # Run a terraform validate
-      # - name: Terraform Validate
-      #   id: validate
-      #   # Run even if formatting fails
-      #   if: success() || failure()
-      #   run: terraform validate
+        # Run even if formatting fails
+        # if: success() || failure()
+        run: |
+          cd $environment
+          
+          terraform validate
 
       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
       - name: Terraform Init
@@ -98,9 +98,6 @@ jobs:
         
         run: |
           cd $environment
-          ls -lah
-          echo '---'
-          ls -lah ../
 
           terraform plan \
             -var-file=../environments/$environment.tfvars
